### ISSUE TITLE
Country list sections

### ISSUE THREAD

**Issue by stief510** [underscopeio/react-native-facebook-account-kit#15]
Is there any way to customize the section header background color in the country list page?
![screen shot 2016-06-15 at 12 48 03 pm](https://cloud.githubusercontent.com/assets/5383963/16089035/6fc2d428-32f7-11e6-8cd0-28da8dfd4493.png)

**Comment by gaguirre** [comment]
It seems it's not possible, at least with the SDK version we are using right now.
I will try updating the SDK and let you know.

**Comment by gaguirre** [comment]
Good news @stief510! It's fixed with new SDK version.
<img width="395" alt="screen shot 2016-06-20 at 10 21 59 pm" src="https://cloud.githubusercontent.com/assets/1652196/16215115/76f0c9e8-3735-11e6-9419-c0a7c8ae1b79.png">

It takes the color from the `inputBackgroundColor` property.

I will publish a new release tomorrow.

**Comment by gaguirre** [comment]
Version **0.2.0** is published and fixes this.
You will need to install the new version and then re-link the AccountKit framework in your iOS project.
