### ISSUE TITLE
Can not use with react native firebase starter project

### ISSUE THREAD

**Issue by tuan072090** [underscopeio/react-native-facebook-account-kit#157]
My project is initialized from [react native firebase starter project here](https://github.com/invertase/react-native-firebase-starter)

It work fine on iOS but on android. 

First, android studio cannot synsc the project because of conflits google play service version. I manualy changed the versions in react-native-account-kit grade file as below

> dependencies {
    implementation 'com.facebook.react:react-native:+'
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation "com.google.android.gms:play-services-auth-base:15.0.1"
    implementation "com.google.android.gms:play-services-auth-api-phone:15.0.1"
    implementation "com.google.android.gms:play-services-auth:15.0.1"
    implementation "com.android.support:appcompat-v7:${SUPPORT_LIB_VERSION}"
    implementation "com.android.support:design:${SUPPORT_LIB_VERSION}"
    implementation ("com.facebook.android:account-kit-sdk:${ACCOUNT_KIT_VERSION}"){
        exclude group: 'com.parse.bolts', module: 'bolts-android';
        exclude group: 'com.parse.bolts', module: 'bolts-applinks';
        exclude group: 'com.parse.bolts', module: 'bolts-tasks';
    }

> }

Then the project is synced successfully, but build failed and get the error "org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
"
this is the error screenshot
[https://gyazo.com/6cddb606659a9160c4c4879109bb9710
](https://gyazo.com/6cddb606659a9160c4c4879109bb9710
)

I spent 2 days to debug but cannot fix it. please safe my life :((((

**Comment by jpgarcia** [comment]
Hi @tuan072090 

I tried what you mentioned with the latest **react-native-firebase-starter** and worked by doing the following steps:

1. Update the `react-native-firebase-starter/android/build.gradle` file and added de `configurations.all` node to force dependencies (no need to modify `react-native-facebook-account-kit` lib)

```java
allprojects {
    repositories {
        mavenLocal()
        jcenter()
        google()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }

        configurations.all {
            resolutionStrategy {
                force "com.android.support:appcompat-v7:27.1.1"
                force "com.android.support:support-v4:27.1.1"
                force "com.google.android.gms:play-services-base:15.0.1"
                force "com.google.android.gms:play-services-auth-base:15.0.1"
                force "com.google.android.gms:play-services-auth-api-phone:15.0.1"
                force "com.google.android.gms:play-services-auth:15.0.1"
            }
        }
    }
}
``` 
2. Update the `react-native-firebase-starter/android/app/src/name/AndroidManifest.xml` file to override the `allowBackup` option:

> Notice the new **xmlns:tools** prop in the **manifest** node and the **android:allowBackup** prop in the **application** node

```java
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.invertase.rnfirebasestarter"
    android:versionCode="1"
    xmlns:tools="http://schemas.android.com/tools"
    android:versionName="1.0">

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      tools:replace="android:allowBackup"
      android:theme="@style/AppTheme">
```

That's it! feel free to reopen the issue if you are still having issues!

**Comment by tuan072090** [comment]
@jpgarcia  thank you so much, it worked perfectly 💃

**Comment by Aung-Myint-Thein** [comment]
Hello, I am using RN 57.5 and react-native-facebook-account-kit 1.1.0. the build was successful but app cannot start by saying "Unfortunately, app has stopped". I have tried the steps mentioned above and issue #159 but still cannot get the app running. iOS is running fine. The issue is only on Android. Our configurations are as follows. Would appreciate if you can take a look and give some suggestions.. Thanks!

android/build.gradle
`
buildscript {
    ext {
        kotlin_version = '1.2.50'
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 26
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion   = "15.0.1"
    }
    repositories {
        google()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven {
            url 'https://maven.fabric.io/public'
        }
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        classpath 'com.google.gms:google-services:3.0.0' // <--- add this
        classpath 'com.google.firebase:firebase-plugins:1.1.5'
        classpath 'io.fabric.tools:gradle:1.25.4'
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url "https://jitpack.io" }
        maven {
          url "https://maven.google.com"
        }
    }
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 28
                buildToolsVersion "28.0.3"
            }
        }
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}`

android/app/build.gradle

`apply plugin: "com.android.application"
apply plugin: "com.google.firebase.firebase-perf"
apply plugin: "io.fabric"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-sentry/sentry.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
    dexOptions {
        jumboMode true
    }
    defaultConfig {
        applicationId "com.myanlearn_for_students"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 15
        versionName "2.0.3"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    configurations {
        all*.exclude group: 'com.android.support', module: 'support-v4'
        all*.exclude group: 'com.android.support', module: 'support-annotations'
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}

dependencies {
    // account kit
    implementation project(':react-native-facebook-account-kit')
    implementation 'com.google.android.gms:play-services-auth-api-phone:15.0.0'

    implementation project(':lottie-react-native')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-smart-splash-screen')
    implementation project(':react-native-spinkit')
    implementation project(':react-native-sentry')    
    implementation 'com.android.support:multidex:1.0.3'
    implementation project(':react-native-firebase')
    implementation project(':react-native-fbsdk')
    implementation project(':react-native-fetch-blob')
    implementation project(':react-native-camera')
    implementation project(':react-native-svg')
    implementation project(':react-native-photo-view')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-image-crop-picker')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.facebook.fresco:animated-gif:1.3.0'
    implementation(project(":react-native-google-signin")){         
        exclude group: "com.google.android.gms" // very important
    }
    implementation ('com.google.android.gms:play-services-auth:15.0.0'){
        force = true;
    }
    
    // Firebase dependencies
    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-core:16.0.4"
    implementation "com.google.firebase:firebase-messaging:17.3.4"
    implementation "com.google.firebase:firebase-invites:16.0.4"
    implementation "com.google.firebase:firebase-perf:16.2.0"
    implementation ('com.crashlytics.sdk.android:crashlytics:2.9.5@aar') {
        transitive = true
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services' // <--- this should be the last line`

Thanks...
